platform :ios, '6.0'
xcodeproj 'Exersite.xcodeproj'
pod 'StyledPageControl',  '~> 1.0'
pod 'RegexKitLite',       '~> 4.0'
pod 'MBProgressHUD',      '~> 0.5'
pod 'TestFlightSDK',      '~> 2.0'
pod 'BugSense',           '~> 3.5'
pod 'AFNetworking',       '~> 1.3.1'
pod 'MMDrawerController', '~> 0.5.1'
pod 'Mantle',             '~> 1.2'
pod 'UIAlertView-Blocks', '~> 0.0.1'
pod 'SBJson',             '~> 3.2'
pod 'Stripe', 			  '~> 1.1.4'
pod 'InAppSettingsKit',   '~> 1.1'
pod 'NSDate+TimeAgo',     '~> 1.0.2'
pod 'EGOCache',           '~> 2.0'